-- ============================================================
-- LAB - Actualizacion de rosters 2026 (desde rosters_2026.md)
-- ============================================================

DO $$
DECLARE
  temp_id UUID;
  arias_id UUID;
  cachorros_id UUID;
  infernales_id UUID;
  daom_id UUID;
  falcons_id UUID;
BEGIN
  SELECT id INTO temp_id FROM temporadas WHERE anio = 2026;
  SELECT id INTO arias_id FROM clubes WHERE slug = 'arias';
  SELECT id INTO cachorros_id FROM clubes WHERE slug = 'cachorros';
  SELECT id INTO infernales_id FROM clubes WHERE slug = 'infernales';
  SELECT id INTO daom_id FROM clubes WHERE slug = 'daom';
  SELECT id INTO falcons_id FROM clubes WHERE slug = 'falcons';

  DELETE FROM jugadores WHERE club_id IN (arias_id, cachorros_id, infernales_id, daom_id, falcons_id);

  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Benjamin Pardo', 'arias-16503fd8ea28', 1, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Franco Salinas', 'arias-0dcb3826dd81', 2, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Rostagno Francisco', 'arias-f3abe4bfa662', 3, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Jeronimo Barbieri', 'arias-873778151370', 4, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Agustin Figueras (R)', 'arias-68e35014271a', 5, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Joaco Bruno', 'arias-82ec1054388c', 6, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Pablo Palacios', 'arias-a484bf1cc18a', 7, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sanchez Elian', 'arias-106c8f1da073', 8, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sanchuli Santiago', 'arias-423e36d0e887', 9, 'shortstop', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Alexis Uriel Bustamante', 'arias-f5fd8f51c078', 10, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gonzalo Cabanillas', 'arias-2e0aff5e8a4c', 11, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Ezequiel Barreto', 'arias-488bb41f237d', 12, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gabriel Barreto', 'arias-943b5bddb212', 13, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Tomas Ligorria', 'arias-29549d093104', 14, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Felipe Britos (R)', 'arias-4341ee3812ee', 15, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Julian Rebollo', 'arias-082cc5f79ca5', 16, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Diego Torres', 'arias-7bef1dfc593f', 17, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Juarez Leandro', 'arias-0216264e293b', 18, 'center_field', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Edgardo Chamo', 'arias-df22178b908f', 19, 'catcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Leo Salazar', 'arias-1daa13aaf596', 20, 'catcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Agustin Tanco', 'arias-d2fa91e79834', 21, 'catcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Federico Tanco', 'arias-5d196b14dc44', 22, 'utility', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Juan Elorza', 'arias-ea24981239ec', 23, 'utility', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Franco Aguero', 'arias-8013763f7ea2', 24, 'utility', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Rodrigo Bruera', 'arias-7c274dfcbd05', 25, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Marco Caruso', 'arias-c203b88fb47e', 26, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Bruno Tartaglia', 'arias-d2d83819b49a', 27, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Mateo Abregu', 'arias-cf0394d26991', 28, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Nicolas Bou', 'arias-9fa055c3cfae', 29, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Luca Annovazzi', 'arias-bc50a8ac482c', 30, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Matias Riha (R)', 'arias-3b0d21a659f9', 31, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Marco Sciarroni', 'arias-91f1bf4a3d8e', 32, 'pitcher', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cuenca Thomas', 'arias-838835909a31', 33, 'utility', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Juarez Leandro', 'arias-7a0dd4f081d0', 34, 'utility', arias_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Acuña, Geronimo', 'cachorros-b8dc8ce19117', 1, 'shortstop', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Alvarado, Nicolas', 'cachorros-55aa7620f59f', 2, 'shortstop', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cortese, Tomas', 'cachorros-ede3bc30066c', 3, 'catcher', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cortez Peña, Samuel Moises', 'cachorros-9a9eb3e11914', 4, 'center_field', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Escalante, Valentino', 'cachorros-4922ba1e050a', 5, 'shortstop', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Guzman Ortega, Jorge Raul', 'cachorros-b2295358ac29', 6, 'pitcher', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Martinez, Tomas Sebastian', 'cachorros-45219916235c', 7, 'center_field', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Schiavoni, Santino', 'cachorros-34b2d1f6604d', 8, 'center_field', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Turlione, Juan Ignacio', 'cachorros-da709d87ba99', 9, 'shortstop', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Velardez, Martin', 'cachorros-cc086b149b0d', 10, 'shortstop', cachorros_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Ramon Bautista', 'infernales-4376da93b44f', 1, 'utility', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Vera Mauro', 'infernales-274701578b6a', 2, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Perez Matias', 'infernales-8e2be9825614', 3, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Flores Facundo', 'infernales-35e51d4b1629', 4, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Almaraz Tomas', 'infernales-6ca6465201a0', 5, 'utility', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Ramon Lucas', 'infernales-f45fe23d1b95', 6, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Postigo Francisco', 'infernales-9e4507fe4214', 7, 'primera_base', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cruz Martin', 'infernales-34ae4e50c8a3', 8, 'center_field', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Zenteno Leonel', 'infernales-c089012963f4', 9, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Alvarez Javier', 'infernales-bb3fcfd81f8d', 10, 'utility', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sotomayor Franco', 'infernales-9b5b23185864', 11, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Granados Santiago', 'infernales-9da5535575fd', 12, 'center_field', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Bisbal Sebastian', 'infernales-790b240ba1ea', 13, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Juarez Emiliano', 'infernales-7f5358590042', 14, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gerez Mateo Santiago', 'infernales-8abb503307a4', 15, 'catcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Talevi Ezequiel', 'infernales-5388b3073050', 16, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gomez Federico', 'infernales-8b39142fa3df', 17, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Zalazar Fabricio', 'infernales-deba6b6c95be', 18, 'center_field', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Rojas Eduardo', 'infernales-0b31b779339b', 19, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gomez Lautaro', 'infernales-24e9ced827d5', 20, 'center_field', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Rodriguez Arnedo Salvador', 'infernales-88a9838d0d80', 21, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sanso Santiago', 'infernales-e69b9df02a3f', 22, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gerez Jose', 'infernales-d833aed1edc6', 23, 'catcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Zalazar Maximo', 'infernales-bae55a5cba92', 24, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Romero Ignacio', 'infernales-eb1756faa0c1', 25, 'catcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Urdaneta Paul David', 'infernales-57425f67e484', 26, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Villalta Joyner', 'infernales-204dbc23090b', 27, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Quiroga Domingo', 'infernales-0bcc59d1f197', 28, 'catcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Pereyra Lucas', 'infernales-2dbdd871bba1', 29, 'pitcher', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Margherita Benjamin', 'infernales-a3e916bf9939', 30, 'center_field', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Alzogaray Baltazar', 'infernales-3fc022003224', 30, 'center_field', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Peyrote Nicolas', 'infernales-beea015723b9', 31, 'shortstop', infernales_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Abarca Lugo Jose Daniel', 'daom-d6cf6f8f1510', 44, 'utility', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Alfonso Manuel Ignacio', 'daom-f7e759ff84db', 29, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Baldovi Matias', 'daom-8cf62b46911d', 15, 'center_field', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Braccini Luca', 'daom-88c9a19d376d', 13, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Brahim Shahir', 'daom-0dcb0f5965d7', 11, 'catcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cerda Junior', 'daom-5f9468e19733', 0, 'utility', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cipriota Jacinto', 'daom-7f5de72c347c', 42, 'shortstop', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('España Delgadillo Sergio Jose', 'daom-236bcc987a2b', 1, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Fontana Sebastian', 'daom-a3f47e54bf79', 10, 'designated_hitter', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Galindo Alvaro', 'daom-c22f7831f409', 66, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Galindo Jesus', 'daom-a1adea168daf', 72, 'center_field', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Garcia Rozada Mateo', 'daom-94ce38e7d215', 14, 'catcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gonzalez Luis', 'daom-a899dddc52b9', 30, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Kramer Agustin', 'daom-17f20c0c0a1e', 95, 'catcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Litzenberguer Andres Jamal', 'daom-6f39ffdb0b61', 25, 'primera_base', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Martinez Nuñez Antonio', 'daom-0b80e74e08e6', 52, 'catcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Morales Aramis', 'daom-40143402adfc', 64, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Pedrouzo Julian', 'daom-bdcba13af478', 27, 'center_field', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Perdomo Yimber Alejandro Leon', 'daom-13caf9528d55', 73, 'center_field', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Prince Jackson Manuel', 'daom-75f374d32111', 5, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Riello Maximiliano', 'daom-a311f5a82888', 33, 'center_field', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Riello Kevin', 'daom-54cabd2a708b', 2, 'pitcher', daom_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Barrientos Rodrigo Nicolás', 'falcons-af705e3521b1', 18, 'shortstop', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Borras Juan Ignacio', 'falcons-0f0439ac5a6b', 23, 'pitcher', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Bressan Tomas', 'falcons-f84d87e39ce7', 4, 'shortstop', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Cadiz Zimba', 'falcons-e14a097cbd6b', 0, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Depen Michael', 'falcons-952551ad186f', 16, 'designated_hitter', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Do Carmo Gabriel', 'falcons-0db0b6bf7dd3', 99, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Garcia Miguel Angel', 'falcons-16ee802ce7a5', 13, 'pitcher', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Gigena Elias', 'falcons-64007b4131ca', 0, 'pitcher', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Guzman Ortega Jorge Raul', 'falcons-3eff9b37f73a', 0, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Lopez Gomez Yaferson', 'falcons-9e597f522acf', 53, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Maestre Arcia Robinson José', 'falcons-d60f5f447e80', 0, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Martin Jonathan', 'falcons-bab2316b3409', 0, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Martin Majul Juan Cruz', 'falcons-be00184bd782', 10, 'shortstop', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Martinez Leonardo', 'falcons-6825c19b8874', 3, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Parra Carlos', 'falcons-1b6eb02068c3', 7, 'pitcher', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Robain Izquiel Johnanderson Jose', 'falcons-2514fe12426c', 0, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Robles Federico', 'falcons-3e7d8c394ae8', 0, 'pitcher', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Robles Matias', 'falcons-e497f259d154', 24, 'center_field', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Rojas Gonzalez Alfredo Alejandro', 'falcons-07eb2fd940e0', 0, 'utility', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sanchez Ismael', 'falcons-247a558b09ae', 77, 'center_field', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sanchez Barrionuevo Eilan', 'falcons-cfa02553c42a', 2, 'center_field', falcons_id, temp_id, true);
  INSERT INTO jugadores (nombre, slug, numero_camiseta, posicion, club_id, temporada_id, activo) VALUES ('Sciarroni Marco', 'falcons-94813ab4864c', 27, 'pitcher', falcons_id, temp_id, true);

  -- Staff tecnico provisto en el archivo fuente (Arias y Popeye/Infernales)
  DELETE FROM staff_clubes WHERE club_id IN (arias_id, infernales_id) AND cargo IN ('Manager','Bench Coach','Pitching Coach','Coach','Jefe de equipo');
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (arias_id, 'Bruera Rodrigo', 'Manager', 1);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (arias_id, 'Tanco Federico', 'Bench Coach', 2);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (arias_id, 'Garcia Roman', 'Pitching Coach', 3);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (arias_id, 'Bou Ariel', 'Coach', 4);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (infernales_id, 'Arnedo Rodolfo', 'Coach', 1);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (infernales_id, 'Sanso Gabriel', 'Coach', 2);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (infernales_id, 'Cukierman Mariano', 'Pitching Coach', 3);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (infernales_id, 'Bisbal Federico', 'Manager', 4);
  INSERT INTO staff_clubes (club_id, nombre, cargo, orden) VALUES (infernales_id, 'Gomez Gustavo', 'Jefe de equipo', 5);
END $$;
